"""sync schema with models

Revision ID: 9adcd82108f8
Revises: 0001
Create Date: 2026-08-10 16:29:52.623730
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9adcd82108f8'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judge_runs', sa.Column('test_case_id', sa.UUID(), nullable=True))
    op.add_column('judge_runs', sa.Column('custom_stdin', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'judge_runs', 'test_cases', ['test_case_id'], ['id'], ondelete='SET NULL')
    op.add_column('test_cases', sa.Column('explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'explanation')
    op.drop_constraint(None, 'judge_runs', type_='foreignkey')
    op.drop_column('judge_runs', 'custom_stdin')
    op.drop_column('judge_runs', 'test_case_id')
    # ### end Alembic commands ###
