"""Safe Exam Browser Config Key verification.

SEB hashes every setting in its .seb config file into a single Config Key (shown by
the Config Tool once "Use Browser Exam Key and Config Key" is ticked). With that
ticked, every request SEB makes carries a header computed as
SHA256(requested_url + config_key_hex). Verifying it here just means recomputing that
same hash server-side and comparing — SEB's own JSON-canonicalization never needs to
be reimplemented because the Config Key itself is generated by the Config Tool, not
by us.
"""

from __future__ import annotations

import hashlib
import logging

from fastapi import HTTPException, Request, status

log = logging.getLogger("exam.seb")

SEB_HEADER_NAMES = ("x-safeexambrowser-configkeyhash", "x-safeexambrowser-requesthash")


def verify_seb_request(request: Request, config_key: str | None) -> None:
    if not config_key:
        # requires_seb is true but no key was ever set — fail closed rather than
        # accepting every request as if the check were disabled.
        raise HTTPException(
            status.HTTP_403_FORBIDDEN,
            "This exam has no Safe Exam Browser configuration set; contact your administrator.",
        )

    received = next(
        (request.headers.get(h) for h in SEB_HEADER_NAMES if request.headers.get(h)),
        None,
    )
    if received is None:
        log.warning(
            "seb: no SEB header present on %s %s — headers seen: %s",
            request.method,
            request.url.path,
            [h for h in request.headers if h.lower().startswith("x-safeexambrowser")],
        )
        raise HTTPException(
            status.HTTP_403_FORBIDDEN,
            "This exam must be taken in Safe Exam Browser.",
        )

    url = str(request.url).split("#", 1)[0]
    expected = hashlib.sha256(f"{url}{config_key}".encode("utf-8")).hexdigest()
    if received.lower() != expected.lower():
        log.warning(
            "seb: hash mismatch — url_hashed=%r config_key=%r received=%s expected=%s "
            "all_seb_headers=%s",
            url,
            config_key,
            received,
            expected,
            {h: v for h, v in request.headers.items() if h.lower().startswith("x-safeexambrowser")},
        )
        raise HTTPException(
            status.HTTP_403_FORBIDDEN,
            "Safe Exam Browser configuration does not match this exam.",
        )
